### ISSUE TITLE
0.3.6.0 does not build with base< 4.8

### ISSUE THREAD

**Issue by ivan-m** [basvandijk/scientific#65]
From my build log (with both GHC 7.6 and 7.8):

```
Downloading scientific-0.3.6.0...
Configuring scientific-0.3.6.0...
Building scientific-0.3.6.0...
Preprocessing library scientific-0.3.6.0...
[1 of 5] Compiling GHC.Integer.Compat ( src/GHC/Integer/Compat.hs, dist/build/GHC/Integer/Compat.o )
[2 of 5] Compiling Utils            ( src/Utils.hs, dist/build/Utils.o )
[3 of 5] Compiling Data.Scientific  ( src/Data/Scientific.hs, dist/build/Data/Scientific.o )
src/Data/Scientific.hs:192:34:
    Not in scope: `*>'
    Perhaps you meant one of these:
      `*' (imported from Prelude),
      `<*>' (imported from Control.Applicative),
      `>>' (imported from Prelude)
Failed to install scientific-0.3.6.0
```

I suspect that [line 125](https://github.com/basvandijk/scientific/blob/master/src/Data/Scientific.hs#L125) needs to include `(*>)` as well.

**Comment by basvandijk** [comment]
Whoops, I wasn't paying attention to the travis builds of GHC < 8 because they were failing for a while due to a failing test dependency. [scientific-0.3.6.1](http://hackage.haskell.org/package/scientific-0.3.6.1) will now build on GHC < 8 and I disabled the test-suite in travis for the GHC < 8 builds so all jobs are green now.

**Comment by ivan-m** [comment]
Ta!
